# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

# @TODO: modify the task-name behavior so that by default, when evaluating a model, the task name is set to "eval/<dataset>/<model>" without having to duplicate the experiment config file
task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
